name: Build benchmarks on Ubuntu
on: [push, pull_request]
jobs:
  BuildBenchmarks:
    # Only Ubuntu for now.
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential ocl-icd-opencl-dev opencl-headers libnuma-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Try to build all benchmarks with a Makefile
        run: make -j4 all
